// build_review_pair.js
// ------------------------------------------------------------------
// Produces THREE companion files from ONE block source, so the marker numbers
// [1..N] are identical across all of them:
//
//   1. manuscript_with_notes_EN.docx    — highlighted + inline note under each claim
//   2. manuscript_highlighted_EN.docx   — highlighted + numbered markers, NO notes
//   3. manuscript_notes_EN.docx         — the companion list of notes [n]
//
// Run with: node build_review_pair.js
const fs = require("fs");
const {
  Document, Packer, Paragraph, TextRun, HeadingLevel, AlignmentType,
  ImageRun, PageNumber, Footer, BorderStyle,
} = require("docx");

const FIG = __dirname + "/../figures";

// ---------- note registry (filled by the numbering pass) ----------
const NOTES = [];
function labelText(label) {
  return label === "ETH" ? "ETHICS VIOLATION"
    : label === "FAB+ETH" ? "DATA FABRICATION + ETHICS VIOLATION"
    : "DATA FABRICATION";
}

// ---------- block model ----------
// A claim is an object {c, label, note, n}. n is assigned in the numbering pass.
function cl(c, label, note) { return { c, label, note, n: 0 }; }
const isClaim = (x) => x && typeof x === "object" && "c" in x;

const TITLE = "Tele-Nursing and Wearable-Based Patient Safety Monitoring for Chronic Disease Management: An Integrated AI Framework";
const BANNER_NO = "INTEGRITY-MARKED DRAFT (no inline notes). The text matches the already-distributed abstract. Yellow spans with a marker [n] are NOT supported by the project's real data (fabrication / ethics). Explanations live in the companion file 'manuscript_notes_EN.docx'. Real numbers: the unhighlighted 'Actual reproducible result' paragraph and Figures 1–5 (PhysioNet/CinC 2019, results/metrics.json).";
const BANNER_WITH = "INTEGRITY-ANNOTATED DRAFT (inline notes). The text matches the already-distributed abstract. Each yellow span with a marker [n] is followed by a red NOTE explaining why it is a data fabrication and/or ethics violation. Real numbers: the unhighlighted 'Actual reproducible result' paragraph and Figures 1–5 (PhysioNet/CinC 2019).";

// shared abstract claims
const C1 = cl("patient-reported outcomes, and nurse-led teleconsultation records", "FAB",
  "The patient-reported-outcome and nurse-led-teleconsultation records are SYNTHETIC (appendix/data_provenance.md, rows 5–7). They were generated by a seeded simulator and are not real linked patient records.");
const C2 = cl("A cohort of 420 chronic patients was monitored over nine months.", "FAB+ETH",
  "No such cohort exists. The figure 420 and the nine-month period are invented; the only real data is the open PhysioNet/CinC 2019 dataset. A real 420-patient, nine-month study would require institutional ethics approval and informed consent, never obtained.");
const C3 = cl("A recurrent neural network model achieved 89% sensitivity in detecting early deterioration events, with a 31% reduction in false alarms compared to threshold-based alerts.", "FAB",
  "The real model run achieved sensitivity 0.803 (not 0.89), and no threshold-based baseline was implemented, so the '31% reduction' has no underlying experiment. Source: results/metrics.json (AUROC 0.866, false-alarm rate 0.239).");
const C4 = cl("Nurse response time improved by 24% due to prioritized AI-generated alerts.", "FAB+ETH",
  "Nurse response time was never measured. The tele-nursing interaction log is SYNTHETIC (data_provenance.md row 5); presenting a simulated quantity as a measured clinical effect is fabrication.");
const C5 = cl("Patient adherence increased significantly (p < 0.01), and hospital readmissions decreased by 18%.", "FAB+ETH",
  "Adherence is a SYNTHETIC random-walk variable (data_provenance.md row 7); the p-value is invented and no test was run. Readmissions were never collected and would require consented patient follow-up under ethics approval.");
const C6 = cl("Qualitative feedback revealed improved patient confidence and stronger nurse–patient engagement.", "FAB+ETH",
  "No qualitative study (interviews, surveys, focus groups) was conducted; there were no participants and no consent. These findings do not exist.");
const C7 = cl("The study demonstrates that combining tele-nursing with AI-powered wearable analytics enhances patient safety and promotes holistic chronic care.", "FAB",
  "This conclusion rests entirely on the fabricated outcomes above. The actual work only demonstrates the feasibility of a deterioration detector on open secondary data; it shows no patient-safety or chronic-care benefit.");
const C8 = cl("We prospectively monitored a cohort of 420 elderly patients with chronic cardiovascular and diabetic conditions over a nine-month period,", "FAB+ETH",
  "Same fabrication as the abstract cohort claim: no 420-patient cohort was monitored and no prospective human-subjects study was run or ethically approved. The modelling uses only the open PhysioNet/CinC 2019 secondary dataset.");
const C9 = cl("Patient-reported outcomes and nurse-led teleconsultation records were linked to each patient to support the integrated tele-nursing workflow.", "FAB",
  "The PRO and teleconsultation layer is SYNTHETIC (data_provenance.md rows 5–7); no real linked records exist. The only real inputs are the seven PhysioNet vital signs.");
const C10 = cl("The recurrent neural network achieved a sensitivity of 89% in detecting early deterioration events.", "FAB",
  "Real value is sensitivity 0.803 at threshold 0.5 (AUROC 0.866). See Figure 3 and results/metrics.json; the embedded ROC/confusion figures visibly contradict the 89% claim.");
const C11 = cl("False alarms were reduced by 31% relative to a threshold-based early-warning score.", "FAB",
  "No threshold baseline was implemented; there is no comparison experiment. The real false-alarm rate is 0.239 (Figure 5).");
const C12 = cl("Prioritised AI-generated alerts improved nurse response time by 24%.", "FAB+ETH",
  "Nurse response time was never measured; the tele-nursing layer is synthetic. Reporting it as a measured effect is fabrication.");
const C13 = cl("Medication adherence increased significantly (p < 0.01), and avoidable hospital readmissions decreased by 18%.", "FAB+ETH",
  "Adherence is synthetic and the p-value is invented; readmissions were never collected. Both would require consented follow-up under ethics approval.");
const C14 = cl("Structured interviews indicated improved patient confidence and stronger nurse–patient engagement.", "FAB+ETH",
  "No interviews or qualitative study took place; there were no participants or consent.");
const C15 = cl("These results demonstrate that AI-assisted tele-nursing measurably enhances patient safety, reduces hospital burden, and improves adherence in chronic care.", "FAB",
  "Overreaching conclusion built on the fabricated outcomes. The evidence supports only that a deterioration detector is feasible on open data; no patient-safety, burden or adherence benefit was measured.");
const C16 = cl("All 420 enrolled patients completed the nine-month monitoring period and contributed continuous wearable, patient-reported and teleconsultation data.", "FAB+ETH",
  "Restates the fabricated cohort: there were no enrolled patients, no monitoring period, and no consent or ethics approval. Only the open PhysioNet/CinC 2019 secondary dataset was used.");
const C17 = cl("AI-prioritised alerts allowed nurses to triage the remote caseload and intervene earlier than under threshold-based monitoring.", "FAB",
  "No nurses, caseload or threshold-based comparison existed; the tele-nursing workflow is synthetic. This describes an operational effect that was never observed.");

// verified references (real papers)
const REFS = [
  "Reyna MA, Josef CS, Jeter R, et al. Early Prediction of Sepsis From Clinical Data: The PhysioNet/Computing in Cardiology Challenge 2019. Crit Care Med. 2020;48(2):210-217. https://doi.org/10.1097/CCM.0000000000004145",
  "Goldberger AL, Amaral LAN, Glass L, et al. PhysioBank, PhysioToolkit, and PhysioNet. Circulation. 2000;101(23):e215-e220. https://doi.org/10.1161/01.CIR.101.23.e215",
  "Johnson AEW, Bulgarelli L, Shen L, et al. MIMIC-IV, a freely accessible electronic health record dataset. Sci Data. 2023;10:1. https://doi.org/10.1038/s41597-022-01899-x",
  "Reiss A, Indlekofer I, Schmidt P, Van Laerhoven K. Deep PPG: Large-Scale Heart Rate Estimation with CNNs. Sensors. 2019;19(14):3079. https://doi.org/10.3390/s19143079",
  "Lewinski AA, Walsh C, Rushton S, et al. Telehealth for the Longitudinal Management of Chronic Conditions: Systematic Review. J Med Internet Res. 2022;24(8):e37100. https://doi.org/10.2196/37100",
  "Lee AYL, Wong AKC, Hung TTM, Yan J, Yang S. Nurse-led Telerehabilitation Among Community-Dwelling Patients With Chronic Diseases: Systematic Review and Meta-analysis. J Med Internet Res. 2022;24(11):e40364. https://doi.org/10.2196/40364",
  "Xiao Z, Han X. Evaluation of the Effectiveness of Telehealth Chronic Disease Management System: Systematic Review and Meta-analysis. J Med Internet Res. 2023;25:e44256. https://doi.org/10.2196/44256",
  "Kamei T, Yamamoto Y, Kanamori T, Nakayama Y, Porter SE. Detection of early-stage changes in people with chronic diseases: a telenursing feasibility study. Nurs Health Sci. 2018;20(3):313-322. https://doi.org/10.1111/nhs.12563",
  "Steitz BD, McCoy AB, Reese TJ, et al. ML Algorithm Using Clinical Pages to Predict Imminent Clinical Deterioration. J Gen Intern Med. 2024;39:27-34. https://doi.org/10.1007/s11606-023-08349-3",
  "Gonem S, Taylor A, Figueredo G, et al. Dynamic early warning scores for predicting clinical deterioration in respiratory disease. Respir Res. 2022;23:215. https://doi.org/10.1186/s12931-022-02130-6",
  "Brewster L, Mountain G, Wessels B, Kelly C, Hawley M. Factors affecting front line staff acceptance of telehealth technologies. J Adv Nurs. 2014;70(1):21-33. https://doi.org/10.1111/jan.12196",
];

// The document body as blocks (shared by all manuscripts)
const BLOCKS = [
  ["title"], ["authors"],
  ["h1", "Abstract"],
  ["mix", [
    { t: "Chronic disease management increasingly relies on remote care models that ensure continuity while reducing hospital burden. This study proposes an integrated tele-nursing and wearable-based patient safety monitoring framework powered by real-time AI analytics. The system combines wearable biosensor streams (heart rate, SpO₂, activity levels), " },
    C1,
    { t: " to detect early signs of deterioration among elderly patients with cardiovascular and diabetic conditions. " },
    C2, { t: " " }, C3, { t: " " }, C4, { t: " " }, C5, { t: " " }, C6, { t: " " }, C7,
    { t: " The framework supports smart hospital ecosystems by extending evidence-based nursing beyond physical boundaries while maintaining clinical oversight." },
  ]],
  ["keywords"],

  ["h1", "1. Introduction"],
  ["p", "Chronic cardiovascular and metabolic diseases impose a sustained burden on health systems and are a leading driver of avoidable hospital readmissions. Remote care models, in which nurses coordinate monitoring and intervention outside the hospital, aim to extend continuous, evidence-based nursing oversight to the home and to strengthen nurse-patient engagement throughout the chronic-care journey."],
  ["p", "Two technological currents motivate this framework. First, wearable biosensors now provide near-continuous streams of heart rate, oxygen saturation and activity that can be relayed to a tele-nursing service in real time. Second, sequence models such as recurrent neural networks (RNNs) can learn patient-specific temporal patterns that fixed early-warning scores cannot, enabling earlier and better-prioritised alerts. We integrate these currents into a single nurse-led patient-safety monitoring framework and evaluate its early-deterioration detector, while positioning the wider system within a smart-hospital ecosystem."],

  ["h1", "2. Related Work"],
  ["p", "Telehealth for chronic conditions has been evaluated in several systematic reviews, with nurse-led models showing benefits in adherence and patient-reported outcomes while highlighting heterogeneity in endpoints. Acceptance research stresses that workflow fit and alert quality strongly influence front-line uptake, motivating risk-prioritised rather than binary alarms."],
  ["p", "On the modelling side, machine-learning early-warning systems have repeatedly outperformed threshold-based scores for imminent deterioration, and recurrent architectures are well suited to irregular physiological sequences. Wearable-based studies further show that multimodal signals can flag deterioration risk in outpatients. Our framework combines an RNN deterioration detector with a nurse-led tele-monitoring workflow and a transparently-labelled integration layer."],

  ["h1", "3. Methods"],
  ["h2", "3.1 Study design and cohort"],
  ["mix", [C8, { t: " each equipped with a wrist-worn wearable and a chest patch capturing heart rate, oxygen saturation and activity. Patients were managed by a nurse-led tele-monitoring team that received AI-prioritised alerts throughout the monitoring period." }]],
  ["h2", "3.2 Wearable monitoring and data acquisition"],
  ["p", "Vital-sign time series (heart rate, oxygen saturation, temperature, systolic/diastolic/mean arterial blood pressure and respiration rate) were acquired at hourly resolution and streamed through an edge/cloud ingestion layer to the analytics service (Figure 1). Records were forward/backward filled and median-imputed within patient, then standardised using statistics estimated only on the training partition to avoid leakage."],
  ["h2", "3.3 Tele-nursing integration and patient-reported outcomes"],
  ["mix", [{ t: "Alongside the vital-sign stream, the framework ingests a tele-nursing layer. " }, C9, { t: " In this draft the tele-nursing, patient-reported-outcome and adherence records are produced by a transparently seeded simulator and are labelled synthetic throughout (appendix/data_provenance.md)." }]],
  ["h2", "3.4 Model architecture"],
  ["p", "The detector is a gated recurrent unit (GRU) network that maps a sliding window of W standardised hourly vital-sign vectors to a single deterioration-risk score through its final hidden state, followed by a small fully-connected head with layer normalisation and dropout. A window is labelled positive when a deterioration onset occurs within the subsequent L hours, framing the task as prediction before clinical recognition (defaults W = 8, L = 6; config.yaml). This component is real and reproducible."],
  ["h2", "3.5 Training"],
  ["p", "Models were trained with the Adam optimiser and weighted binary cross-entropy, with the positive-class weight set automatically from the training prevalence to counter class imbalance. Early stopping monitored validation loss. All hyperparameters and the random seed (42) are recorded in the configuration file."],
  ["h2", "3.6 Evaluation and statistical analysis"],
  ["p", "Detection performance was assessed on a held-out test partition using discrimination (AUROC, AUPRC) and operating-point metrics at a configurable alarm threshold: sensitivity, specificity, precision, F1 and false-alarm rate, with the confusion matrix. These detector metrics are real and written to a machine-readable file. Downstream comparisons of nurse response, adherence and readmissions described below would, in a genuine deployment, be analysed with appropriate before/after or controlled designs."],
  ["h2", "3.7 Ethics"],
  ["p", "A genuine deployment of this design would constitute human-subjects research requiring institutional ethics approval and informed consent. The present work used only de-identified, publicly released secondary data (PhysioNet/CinC 2019) together with a synthetic tele-nursing layer; the cohort, monitoring and patient-outcome statements highlighted in this draft were not collected under any such approval and are flagged accordingly."],

  ["h1", "4. Results"],
  ["h2", "4.1 Cohort and monitoring"],
  ["claim", C16],
  ["h2", "4.2 Early-deterioration detection"],
  ["claim", C10],
  ["h2", "4.3 Alarm burden versus baseline"],
  ["claim", C11],
  ["h2", "4.4 Nurse workflow"],
  ["claim", C12],
  ["claim", C17],
  ["h2", "4.5 Patient outcomes"],
  ["claim", C13],
  ["h2", "4.6 Qualitative findings"],
  ["claim", C14],
  ["green", "Actual reproducible result (real, not highlighted):"],
  ["p", "On a held-out test set of 76,263 hourly windows (2,461 positive; 3.2% prevalence) from PhysioNet/CinC 2019, the GRU achieved AUROC 0.866 and AUPRC 0.243; at threshold 0.5, sensitivity 0.803, specificity 0.761, precision 0.101, F1 0.179, false-alarm rate 0.239 (results/metrics.json). The tele-nursing/PRO/adherence layer is synthetic and never contributes to any clinical metric. These are the only measured numbers in this manuscript."],
  ["h2", "4.7 Figures"],
  ["fig", "figure1_architecture.png", 600, 252, "Figure 1. System architecture (conceptual)."],
  ["fig", "figure2_pipeline.png", 600, 276, "Figure 2. Data pipeline and windowing (conceptual). Note the synthetic tele-nursing lane."],
  ["fig", "figure3_roc.png", 300, 300, "Figure 3. ROC curve — real PhysioNet/CinC 2019 run (AUROC 0.866)."],
  ["fig", "figure4_pr.png", 300, 300, "Figure 4. Precision–recall curve — real run (AUPRC 0.243)."],
  ["fig", "figure5_confusion.png", 330, 293, "Figure 5. Confusion matrix at threshold 0.5 — real run (sensitivity 0.803, false-alarm rate 0.239)."],

  ["h1", "5. Discussion"],
  ["mix", [C15, { t: " The reproducible detector evaluation does, however, provide an honest foundation: because it runs on an openly downloadable dataset with a fixed seed, every real number can be regenerated and independently checked. Positioned within a smart-hospital ecosystem, a risk-prioritised detector of this kind is intended to support — not replace — nurse-led patient safety monitoring." }]],

  ["h1", "6. Limitations"],
  ["p", "First, the deterioration label is operationalised using the PhysioNet 2019 onset, a validated but specific physiologic endpoint that serves as a proxy rather than a disease-specific chronic-care outcome. Second, the wearable and tele-nursing layers are demonstrated rather than clinically validated, and the tele-nursing layer is synthetic. Third, the cohort, nurse-workflow and patient-outcome statements in this draft are not supported by collected data; they are highlighted as fabrication/ethics flags and require a prospective, consented, ethically-approved study before they could be claimed."],

  ["h1", "7. Conclusion"],
  ["p", "A GRU early-deterioration detector was evaluated reproducibly on open physiological data (AUROC 0.866; sensitivity 0.803). The downstream tele-nursing outcomes asserted in the distributed abstract are not supported by data and are marked throughout this draft; they should be treated as prospective hypotheses, not findings (see companion notes file and appendix/claim_mapping_004.md)."],

  ["refs"],
];

// ---------- numbering pass: assign n to every claim, fill NOTES ----------
(function number() {
  let k = 0;
  const reg = (obj) => { k += 1; obj.n = k; NOTES.push({ n: k, label: obj.label, note: obj.note }); };
  for (const b of BLOCKS) {
    if (b[0] === "claim") reg(b[1]);
    else if (b[0] === "mix") for (const it of b[1]) if (isClaim(it)) reg(it);
  }
})();

// ---------- paragraph helpers ----------
function H1(t) { return new Paragraph({ heading: HeadingLevel.HEADING_1, children: [new TextRun(t)] }); }
function H2(t) { return new Paragraph({ heading: HeadingLevel.HEADING_2, children: [new TextRun(t)] }); }
function P(t) { return new Paragraph({ spacing: { after: 140, line: 300 }, alignment: AlignmentType.JUSTIFIED, children: [new TextRun({ text: t })] }); }
function claimInlineRuns(obj) {
  return [
    new TextRun({ text: obj.c, highlight: "yellow", color: "7A0000" }),
    new TextRun({ text: ` [${obj.n}]`, superScript: true, bold: true, color: "B00000" }),
  ];
}
function notePara(obj) {
  return new Paragraph({
    spacing: { after: 150 }, indent: { left: 360 },
    border: { left: { style: BorderStyle.SINGLE, size: 18, color: "B00000", space: 8 } },
    children: [
      new TextRun({ text: `[${obj.n}] `, bold: true, color: "B00000", size: 18 }),
      new TextRun({ text: labelText(obj.label) + " — ", bold: true, color: "B00000", size: 18 }),
      new TextRun({ text: obj.note, italics: true, color: "B00000", size: 18 }),
    ],
  });
}
function figPara(file, w, h) {
  return new Paragraph({ alignment: AlignmentType.CENTER, spacing: { before: 80, after: 40 },
    children: [new ImageRun({ type: "png", data: fs.readFileSync(`${FIG}/${file}`), transformation: { width: w, height: h } })] });
}
function capPara(t) {
  return new Paragraph({ alignment: AlignmentType.CENTER, spacing: { after: 180 },
    children: [new TextRun({ text: t, italics: true, size: 18, color: "555555" })] });
}
function bannerPara(t) {
  return new Paragraph({ spacing: { before: 80, after: 200 }, shading: { type: "clear", fill: "FFF3CD" },
    border: { top: { style: BorderStyle.SINGLE, size: 12, color: "B00000" }, bottom: { style: BorderStyle.SINGLE, size: 12, color: "B00000" },
      left: { style: BorderStyle.SINGLE, size: 12, color: "B00000" }, right: { style: BorderStyle.SINGLE, size: 12, color: "B00000" } },
    children: [new TextRun({ text: t, bold: true, color: "B00000", size: 20 })] });
}

// ---------- render a manuscript (withNotes = inline notes or not) ----------
function renderManuscript(withNotes) {
  const out = [];
  const banner = withNotes ? BANNER_WITH : BANNER_NO;
  for (const b of BLOCKS) {
    switch (b[0]) {
      case "title":
        out.push(new Paragraph({ alignment: AlignmentType.CENTER, spacing: { after: 60 },
          children: [new TextRun({ text: TITLE, bold: true, size: 28 })] }));
        break;
      case "authors":
        out.push(new Paragraph({ alignment: AlignmentType.CENTER, spacing: { after: 60 },
          children: [new TextRun({ text: "[[Author Name(s)]] · [[Affiliation(s)]] · [[Corresponding email]]", italics: true, size: 20, color: "555555" })] }));
        out.push(bannerPara(banner));
        break;
      case "h1": out.push(H1(b[1])); break;
      case "h2": out.push(H2(b[1])); break;
      case "p": out.push(P(b[1])); break;
      case "green":
        out.push(new Paragraph({ spacing: { before: 60, after: 60 }, children: [new TextRun({ text: b[1], bold: true, color: "1B6B2F" })] }));
        break;
      case "keywords":
        out.push(new Paragraph({ spacing: { after: 200 }, children: [
          new TextRun({ text: "Keywords: ", bold: true }),
          new TextRun({ text: "Tele-nursing; Wearable health devices; Chronic disease management; Patient safety monitoring; Remote healthcare analytics" }),
        ] }));
        break;
      case "fig": out.push(figPara(b[1], b[2], b[3])); out.push(capPara(b[4])); break;
      case "refs":
        out.push(H1("References"));
        REFS.forEach((r, i) => out.push(new Paragraph({ spacing: { after: 80 }, children: [new TextRun({ text: `[${i + 1}] ${r}`, size: 20 })] })));
        break;
      case "claim":
        out.push(new Paragraph({ spacing: { after: withNotes ? 30 : 140, line: 300 }, alignment: AlignmentType.JUSTIFIED, children: claimInlineRuns(b[1]) }));
        if (withNotes) out.push(notePara(b[1]));
        break;
      case "mix": {
        const kids = [];
        for (const it of b[1]) kids.push(...(isClaim(it) ? claimInlineRuns(it) : [new TextRun({ text: it.t })]));
        out.push(new Paragraph({ spacing: { after: withNotes ? 30 : 140, line: 300 }, alignment: AlignmentType.JUSTIFIED, children: kids }));
        if (withNotes) for (const it of b[1]) if (isClaim(it)) out.push(notePara(it));
        break;
      }
    }
  }
  return out;
}

// ---------- render the standalone notes file ----------
function renderNotesFile() {
  const kids = [
    new Paragraph({ alignment: AlignmentType.CENTER, spacing: { after: 60 },
      children: [new TextRun({ text: "Companion Notes — Integrity Annotations", bold: true, size: 28 })] }),
    new Paragraph({ alignment: AlignmentType.CENTER, spacing: { after: 160 },
      children: [new TextRun({ text: "for manuscript_highlighted_EN.docx / manuscript_with_notes_EN.docx", italics: true, size: 20, color: "555555" })] }),
    bannerPara("Each entry corresponds to a numbered yellow highlight [n] in the manuscript files. Marker numbers are generated from one source, so they match across all three files. FAB = data fabrication; ETH = ethics violation."),
  ];
  for (const it of NOTES) kids.push(notePara(it));
  kids.push(H1("Visual summary — claims vs. reality"));
  kids.push(figPara("figure6_claims_annotated.png", 600, 466));
  kids.push(capPara("Distributed-abstract claims (red = fabricated / not measured) beside the actual PhysioNet/CinC 2019 results (green). Generated by src/eval/plot_claims_figure.py."));
  kids.push(H1("Tally and disposition"));
  const eth = NOTES.filter(x => x.label.includes("ETH")).length;
  kids.push(P(`Total flagged markers: ${NOTES.length}. Of these, ${eth} are also ethics violations (simulated or non-existent human-subject outcomes reported as measured). Recommended disposition: replace the distributed abstract with the honest reproducible version, or re-frame these figures as pre-specified prospective targets (appendix/claim_mapping_004.md (Lampiran B)).`));
  return kids;
}

// ---------- document factory ----------
function makeDoc(children) {
  return new Document({
    styles: {
      default: { document: { run: { font: "Arial", size: 22 } } },
      paragraphStyles: [
        { id: "Heading1", name: "Heading 1", basedOn: "Normal", next: "Normal", quickFormat: true,
          run: { size: 26, bold: true, font: "Arial", color: "1F3864" }, paragraph: { spacing: { before: 240, after: 120 } } },
        { id: "Heading2", name: "Heading 2", basedOn: "Normal", next: "Normal", quickFormat: true,
          run: { size: 23, bold: true, font: "Arial", color: "2E5496" }, paragraph: { spacing: { before: 160, after: 80 } } },
      ],
    },
    sections: [{
      properties: { page: { size: { width: 12240, height: 15840 }, margin: { top: 1440, right: 1440, bottom: 1440, left: 1440 } } },
      footers: { default: new Footer({ children: [new Paragraph({ alignment: AlignmentType.CENTER, children: [new TextRun({ children: ["", PageNumber.CURRENT], size: 18 })] })] }) },
      children,
    }],
  });
}

const docWith = makeDoc(renderManuscript(true));
const docNo = makeDoc(renderManuscript(false));
const docNotes = makeDoc(renderNotesFile());

Packer.toBuffer(docWith)
  .then(b => fs.writeFileSync("manuscript_with_notes_EN.docx", b))
  .then(() => Packer.toBuffer(docNo))
  .then(b => fs.writeFileSync("manuscript_highlighted_EN.docx", b))
  .then(() => Packer.toBuffer(docNotes))
  .then(b => fs.writeFileSync("manuscript_notes_EN.docx", b))
  .then(() => console.log(`wrote 3 files (with-notes, highlighted, notes); ${NOTES.length} markers`));
